version: "3.2"

services:
  dev:
    container_name: appchain-trustrecruit
    image: paritytech/ci-linux:974ba3ac-20201006
    working_dir: /var/www/appchain-trustrecruit
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/appchain-trustrecruit/.cargo
    volumes:
      - .:/var/www/appchain-trustrecruit
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "cargo build --release && ./target/release/appchain-trustrecruit --dev --ws-external"
